language: php

php:
  - 5.5
  - 5.6

env:
  WP_CONFIG: ./wordpress/wp-config.php
  URL_BASE: http://localhost:8000
  DISPLAY: ":99.0"

before_script:
  - rvm install $(< .ruby-version)
  - rvm use $(< .ruby-version)
  - ruby --version
  - bundle install
  - ./travis_setup.sh
  - "php -S 0.0.0.0:8000 -t ./wordpress/ &"
  - "sh -e /etc/init.d/xvfb start"

script: rake

notifications:
  irc: "irc.freenode.org#slab"
