# Travis
language: ruby

rvm: 2.2

# Specify version of WordPress to test against
# WP_VERSION = WordPress version number (use 'master' for SVN trunk)
# WP_MULTISITE = whether to test in multisite (0 or 1)
env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "bundle install"
  - "echo ls"

# Grab the setup script and execute
before_script:
  - wget https://raw.githubusercontent.com/waynegraham/wordpress-theme-tests/master/setup/setup.sh
  - source setup.sh

script: bundle exec rspec
