language: php

php:
  - 5.5
  - 5.6

env:
  WP_CONFIG: ./wordpress/wp-config.php
  DB_USER: travis
  DB_PASSWORD: ""
  URL_BASE: http://localhost:8000

before_script:
  - echo RUBY
  - echo `ruby --version`
  - echo RVM
  - echo `which rvm`
  - bundle install
  - ./travis_setup.sh
  - php -S 0.0.0.0:8000 -t ./wordpress/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: rake

notifications:
  irc: "irc.freenode.org#slab"
