# Travis
language: ruby

rvm: 2.2

# Specify version of WordPress to test against
#
# WP_VERSION = WordPress version number (use 'master' for SVN trunk)
# WP_MULTISITE = whether to test in multisite (0 or 1)
env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "bundle install"
  - "echo ls"

# Grab the setup script and execute
before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # swap stuff around
  - wget https://raw.githubusercontent.com/waynegraham/wordpress-theme-tests/master/setup/setup.sh
  - source setup.sh

script: cd /tmp/wordpress/wp-content/themes/ivanhoe && bundle exec rspec spec
