# standard jekyll configuration

permalink: /:categories/:title/
highlighter:  pygments
markdown: rdiscount
exclude: ['readme.md', 'Procfile', 'config.rb', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock']
show_drafts: true

title: Ivanhoe
domain: http://ivanhoe.scholarslab.org
